"""Calibration and selective-risk analysis for controlled multi-seed checkpoints.

This script consumes ``controlled_logits.npz`` archives generated by
``export_controlled_logits.py``.  A scalar temperature is fitted using only the
independent validation labels, then frozen before test ECE, NLL, multiclass
Brier score, AURC, reliability bins, and risk--coverage curves are calculated.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import minimize_scalar
from scipy.stats import t as student_t

from make_probability_diagnostics import (
    aurc,
    ece,
    multiclass_brier,
    nll,
    reliability_bins,
)


def softmax(logits: np.ndarray, temperature: float = 1.0) -> np.ndarray:
    values = logits / temperature
    values -= values.max(axis=1, keepdims=True)
    exponentials = np.exp(values)
    return exponentials / exponentials.sum(axis=1, keepdims=True)


def fit_temperature(logits: np.ndarray, labels: np.ndarray) -> float:
    def objective(log_temperature: float) -> float:
        probabilities = softmax(logits, np.exp(log_temperature))
        selected = probabilities[np.arange(len(labels)), labels].clip(1e-12)
        return float(-np.log(selected).mean())

    result = minimize_scalar(objective, bounds=(-3.0, 3.0), method="bounded")
    return float(np.exp(result.x))


DATASETS = ("PV", "DS1", "DS2")
DISPLAY_NAMES = {
    "PV": "NPD-Rice-COCO-43",
    "DS1": "MultiCrop-88",
    "DS2": "Agri-Foundation-145k",
}
CONFIGURATIONS = ("flat", "dual_none")
CALIBRATIONS = ("raw", "temperature_scaled")
METRIC_COLUMNS = (
    "ece15_pct",
    "nll",
    "multiclass_brier",
    "aurc",
)
COLOURS = {"flat": "#315B7D", "dual_none": "#2E7D5B"}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def validate_arrays(
    validation_logits: np.ndarray,
    validation_labels: np.ndarray,
    test_logits: np.ndarray,
    test_labels: np.ndarray,
    class_count: int | None,
) -> None:
    if validation_logits.ndim != 2 or test_logits.ndim != 2:
        raise ValueError("Condition logits must be two-dimensional")
    if validation_logits.shape[0] != len(validation_labels):
        raise ValueError("Validation logits and labels have different lengths")
    if test_logits.shape[0] != len(test_labels):
        raise ValueError("Test logits and labels have different lengths")
    if validation_logits.shape[1] != test_logits.shape[1]:
        raise ValueError("Validation and test class counts differ")
    if class_count and validation_logits.shape[1] != class_count:
        raise ValueError("Archive class count differs from its provenance")
    for name, logits in (
        ("validation", validation_logits),
        ("test", test_logits),
    ):
        if not np.isfinite(logits).all():
            raise ValueError(f"{name} logits contain a non-finite value")
    for name, labels, rows in (
        ("validation", validation_labels, validation_logits.shape[0]),
        ("test", test_labels, test_logits.shape[0]),
    ):
        if labels.shape != (rows,):
            raise ValueError(f"{name} labels have an unexpected shape")
        if labels.min() < 0 or labels.max() >= validation_logits.shape[1]:
            raise ValueError(f"{name} labels fall outside the class range")


def load_logit_arrays(
    run_dir: Path,
    archive_name: str,
    dataset: str,
    configuration: str,
    seed: int,
    check_hash: bool,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, str]:
    """Load either exporter output or native manifest-run val/test archives."""

    combined_path = run_dir / archive_name
    if combined_path.is_file():
        provenance_path = combined_path.with_suffix(".json")
        if not provenance_path.is_file():
            raise FileNotFoundError(provenance_path)
        provenance = json.loads(provenance_path.read_text(encoding="utf-8"))
        expected_identity = {
            "dataset": dataset,
            "configuration": configuration,
            "seed": seed,
        }
        observed_identity = {
            key: provenance.get(key) for key in expected_identity
        }
        if observed_identity != expected_identity:
            raise ValueError(
                f"Archive provenance/path identity mismatch for {combined_path}: "
                f"{observed_identity} != {expected_identity}"
            )
        if check_hash and sha256(combined_path) != provenance.get("archive_sha256"):
            raise ValueError(f"Archive hash mismatch: {combined_path}")
        with np.load(combined_path) as archive:
            required = {
                "validation_condition_logits",
                "validation_labels",
                "test_condition_logits",
                "test_labels",
            }
            missing = required.difference(archive.files)
            if missing:
                raise ValueError(
                    f"Logit archive is missing arrays: {sorted(missing)}"
                )
            validation_logits = archive[
                "validation_condition_logits"
            ].astype(np.float64)
            validation_labels = archive["validation_labels"].astype(int)
            test_logits = archive["test_condition_logits"].astype(np.float64)
            test_labels = archive["test_labels"].astype(int)
        class_count = len(provenance.get("condition_classes", [])) or None
        validate_arrays(
            validation_logits,
            validation_labels,
            test_logits,
            test_labels,
            class_count,
        )
        return (
            validation_logits,
            validation_labels,
            test_logits,
            test_labels,
            "combined_controlled_logits",
        )

    validation_path = run_dir / "val_logits.npz"
    test_path = run_dir / "test_logits.npz"
    protocol_path = run_dir / "run_protocol.json"
    completion_path = run_dir / "COMPLETE.json"
    if not (
        validation_path.is_file()
        and test_path.is_file()
        and protocol_path.is_file()
        and completion_path.is_file()
    ):
        raise FileNotFoundError(f"No complete logit source in {run_dir}")
    protocol = json.loads(protocol_path.read_text(encoding="utf-8"))
    completion = json.loads(completion_path.read_text(encoding="utf-8"))
    expected_identity = {
        "dataset_label": dataset,
        "configuration": configuration,
        "seed": seed,
    }
    observed_identity = {key: protocol.get(key) for key in expected_identity}
    if observed_identity != expected_identity:
        raise ValueError(
            f"Manifest-run identity mismatch for {run_dir}: "
            f"{observed_identity} != {expected_identity}"
        )
    if check_hash:
        expected_validation_hash = completion.get("validation_logits_sha256")
        expected_test_hash = completion.get("test_logits_sha256")
        if sha256(validation_path) != expected_validation_hash:
            raise ValueError(f"Validation-logit hash mismatch: {validation_path}")
        if sha256(test_path) != expected_test_hash:
            raise ValueError(f"Test-logit hash mismatch: {test_path}")
    with np.load(validation_path) as archive:
        validation_logits = archive["condition_logits"].astype(np.float64)
        validation_labels = archive["labels"].astype(int)
        validation_manifest = (
            str(archive["manifest_sha256"].item())
            if "manifest_sha256" in archive.files
            else None
        )
    with np.load(test_path) as archive:
        test_logits = archive["condition_logits"].astype(np.float64)
        test_labels = archive["labels"].astype(int)
        test_manifest = (
            str(archive["manifest_sha256"].item())
            if "manifest_sha256" in archive.files
            else None
        )
    protocol_manifest = protocol.get("manifest_sha256")
    if protocol_manifest and (
        validation_manifest != protocol_manifest
        or test_manifest != protocol_manifest
    ):
        raise ValueError(
            f"Logit/experiment manifest mismatch for {run_dir}: "
            f"protocol={protocol_manifest}, val={validation_manifest}, "
            f"test={test_manifest}"
        )
    class_count = len(protocol.get("condition_classes", [])) or None
    validate_arrays(
        validation_logits,
        validation_labels,
        test_logits,
        test_labels,
        class_count,
    )
    return (
        validation_logits,
        validation_labels,
        test_logits,
        test_labels,
        "native_manifest_val_test_logits",
    )


def risk_coverage_rows(
    dataset: str,
    configuration: str,
    seed: int,
    calibration: str,
    labels: np.ndarray,
    probabilities: np.ndarray,
    points: int,
) -> list[dict]:
    confidence = probabilities.max(axis=1)
    errors = probabilities.argmax(axis=1) != labels
    order = np.argsort(-confidence, kind="mergesort")
    cumulative_errors = np.cumsum(errors[order])
    counts = np.unique(
        np.maximum(
            1,
            np.rint(np.linspace(0.01, 1.0, points) * len(labels)).astype(int),
        )
    )
    rows = []
    for count in counts:
        index = int(count - 1)
        rows.append(
            {
                "dataset": dataset,
                "configuration": configuration,
                "seed": seed,
                "calibration": calibration,
                "coverage": count / len(labels),
                "retained_images": int(count),
                "selective_risk_pct": 100
                * float(cumulative_errors[index] / count),
                "confidence_threshold": float(confidence[order][index]),
            }
        )
    return rows


def metric_summary(per_run: pd.DataFrame) -> pd.DataFrame:
    rows: list[dict] = []
    for keys, group in per_run.groupby(
        ["dataset", "configuration", "calibration"], sort=True
    ):
        dataset, configuration, calibration = keys
        for metric in METRIC_COLUMNS:
            values = group[metric].to_numpy(float)
            mean = float(values.mean())
            standard_deviation = (
                float(values.std(ddof=1)) if len(values) > 1 else np.nan
            )
            if len(values) > 1:
                half_width = float(
                    student_t.ppf(0.975, len(values) - 1)
                    * standard_deviation
                    / np.sqrt(len(values))
                )
                lower, upper = mean - half_width, mean + half_width
            else:
                lower = upper = np.nan
            rows.append(
                {
                    "dataset": dataset,
                    "configuration": configuration,
                    "calibration": calibration,
                    "metric": metric,
                    "seeds": len(values),
                    "mean": mean,
                    "std": standard_deviation,
                    "t_95ci_lower": lower,
                    "t_95ci_upper": upper,
                }
            )
    return pd.DataFrame(rows)


def paired_calibration_changes(per_run: pd.DataFrame) -> pd.DataFrame:
    index = ["dataset", "configuration", "seed"]
    raw = (
        per_run[per_run["calibration"] == "raw"]
        .set_index(index)
        .sort_index()
    )
    scaled = (
        per_run[per_run["calibration"] == "temperature_scaled"]
        .set_index(index)
        .sort_index()
    )
    common = raw.index.intersection(scaled.index)
    rows: list[dict] = []
    for key in common:
        for metric in METRIC_COLUMNS:
            rows.append(
                {
                    "dataset": key[0],
                    "configuration": key[1],
                    "seed": key[2],
                    "metric": metric,
                    "raw": float(raw.loc[key, metric]),
                    "temperature_scaled": float(scaled.loc[key, metric]),
                    "scaled_minus_raw": float(
                        scaled.loc[key, metric] - raw.loc[key, metric]
                    ),
                }
            )
    return pd.DataFrame(rows)


def plot_probability_quality(
    per_run: pd.DataFrame,
    output_dir: Path,
) -> None:
    datasets = [name for name in DATASETS if name in set(per_run["dataset"])]
    fig, axes = plt.subplots(
        len(datasets),
        2,
        figsize=(7.3, 2.25 * len(datasets)),
        squeeze=False,
        constrained_layout=True,
    )
    for row_index, dataset in enumerate(datasets):
        selected = per_run[per_run["dataset"] == dataset]
        for column, (metric, label) in enumerate(
            (("ece15_pct", "ECE (%)"), ("nll", "NLL"))
        ):
            axis = axes[row_index, column]
            x = np.arange(len(CONFIGURATIONS), dtype=float)
            width = 0.33
            for calibration_index, calibration in enumerate(CALIBRATIONS):
                means, errors = [], []
                for configuration in CONFIGURATIONS:
                    values = selected[
                        (selected["configuration"] == configuration)
                        & (selected["calibration"] == calibration)
                    ][metric].to_numpy(float)
                    means.append(float(values.mean()) if len(values) else np.nan)
                    errors.append(
                        float(values.std(ddof=1)) if len(values) > 1 else 0.0
                    )
                offset = (calibration_index - 0.5) * width
                axis.bar(
                    x + offset,
                    means,
                    width=width,
                    yerr=errors,
                    capsize=2.5,
                    color="#B7C8D8" if calibration == "raw" else "#2E7D5B",
                    edgecolor="#274C5E",
                    linewidth=0.6,
                    label=calibration.replace("_", " ").title(),
                )
            axis.set_xticks(x, ["Flat", "Dual"])
            axis.set_ylabel(label)
            axis.grid(axis="y", alpha=0.2)
            if column == 0:
                axis.text(
                    -0.25,
                    1.03,
                    DISPLAY_NAMES[dataset],
                    transform=axis.transAxes,
                    fontweight="bold",
                    va="bottom",
                )
            if row_index == 0 and column == 1:
                axis.legend(frameon=False, fontsize=8)
    for suffix, options in (("pdf", {}), ("png", {"dpi": 400})):
        fig.savefig(
            output_dir / f"controlled_probability_quality.{suffix}",
            bbox_inches="tight",
            facecolor="white",
            **options,
        )
    plt.close(fig)


def plot_risk_coverage(curves: pd.DataFrame, output_dir: Path) -> None:
    datasets = [name for name in DATASETS if name in set(curves["dataset"])]
    fig, axes = plt.subplots(
        1,
        len(datasets),
        figsize=(7.3, 2.65),
        squeeze=False,
        constrained_layout=True,
    )
    for column, dataset in enumerate(datasets):
        axis = axes[0, column]
        selected = curves[
            (curves["dataset"] == dataset)
            & (curves["calibration"] == "temperature_scaled")
        ]
        for configuration in CONFIGURATIONS:
            group = selected[selected["configuration"] == configuration]
            pivot = group.pivot_table(
                index="coverage",
                columns="seed",
                values="selective_risk_pct",
            ).sort_index()
            if pivot.empty:
                continue
            mean = pivot.mean(axis=1)
            standard_error = pivot.std(axis=1, ddof=1) / np.sqrt(
                pivot.notna().sum(axis=1)
            )
            axis.plot(
                100 * pivot.index,
                mean,
                color=COLOURS[configuration],
                linewidth=1.6,
                label="Flat" if configuration == "flat" else "Dual",
            )
            if pivot.shape[1] > 1:
                critical = float(student_t.ppf(0.975, pivot.shape[1] - 1))
                axis.fill_between(
                    100 * pivot.index.to_numpy(),
                    (mean - critical * standard_error).clip(lower=0).to_numpy(),
                    (mean + critical * standard_error).to_numpy(),
                    color=COLOURS[configuration],
                    alpha=0.14,
                    linewidth=0,
                )
        axis.set_title(DISPLAY_NAMES[dataset], fontweight="bold", fontsize=9)
        axis.set_xlabel("Coverage (%)")
        axis.grid(alpha=0.2)
        if column == 0:
            axis.set_ylabel("Selective error (%)")
        if column == len(datasets) - 1:
            axis.legend(frameon=False, fontsize=8)
    for suffix, options in (("pdf", {}), ("png", {"dpi": 400})):
        fig.savefig(
            output_dir / f"controlled_risk_coverage.{suffix}",
            bbox_inches="tight",
            facecolor="white",
            **options,
        )
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--package-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
    )
    parser.add_argument("--runs-root", type=Path, default=None)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--archive-name", default="controlled_logits.npz")
    parser.add_argument("--datasets", nargs="+", choices=DATASETS, default=list(DATASETS))
    parser.add_argument(
        "--configurations",
        nargs="+",
        choices=CONFIGURATIONS,
        default=list(CONFIGURATIONS),
    )
    parser.add_argument("--seeds", nargs="+", type=int, default=None)
    parser.add_argument("--risk-coverage-points", type=int, default=200)
    parser.add_argument("--target-seeds", type=int, default=10)
    parser.add_argument("--strict-target", action="store_true")
    parser.add_argument("--skip-hash-check", action="store_true")
    parser.add_argument("--no-figures", action="store_true")
    args = parser.parse_args()
    if args.risk_coverage_points < 20:
        raise ValueError("--risk-coverage-points must be at least 20")
    package_root = args.package_root.resolve()
    runs_root = (
        args.runs_root.resolve()
        if args.runs_root
        else package_root / "results/revised/e2e_ablation"
    )
    output_dir = (
        args.output_dir.resolve()
        if args.output_dir
        else runs_root / "controlled_calibration"
    )
    output_dir.mkdir(parents=True, exist_ok=True)
    requested_seeds = set(args.seeds) if args.seeds is not None else None
    metric_rows: list[dict] = []
    reliability_rows: list[dict] = []
    curve_rows: list[dict] = []
    audit_rows: list[dict] = []

    for dataset in args.datasets:
        for configuration in args.configurations:
            run_directories = sorted(
                path
                for path in runs_root.rglob("seed_*")
                if path.is_dir()
                and len(path.parts) >= 3
                and path.parts[-3] == dataset
                and path.parts[-2] == configuration
                and (
                    (path / args.archive_name).is_file()
                    or (
                        (path / "COMPLETE.json").is_file()
                        and (path / "val_logits.npz").is_file()
                        and (path / "test_logits.npz").is_file()
                    )
                )
            )
            seen_seeds: list[int] = []
            for run_dir in run_directories:
                seed = int(run_dir.name.removeprefix("seed_"))
                if requested_seeds is not None and seed not in requested_seeds:
                    continue
                if seed in seen_seeds:
                    raise ValueError(
                        f"Duplicate {dataset}/{configuration}/seed_{seed} under "
                        f"{runs_root}; pass a single experiment directory"
                    )
                (
                    validation_logits,
                    validation_labels,
                    test_logits,
                    test_labels,
                    logit_source,
                ) = load_logit_arrays(
                    run_dir,
                    args.archive_name,
                    dataset,
                    configuration,
                    seed,
                    check_hash=not args.skip_hash_check,
                )
                temperature = fit_temperature(validation_logits, validation_labels)
                probabilities = {
                    "raw": softmax(test_logits),
                    "temperature_scaled": softmax(test_logits, temperature),
                }
                for calibration, probability in probabilities.items():
                    predictions = probability.argmax(axis=1)
                    metric_rows.append(
                        {
                            "dataset": dataset,
                            "configuration": configuration,
                            "seed": seed,
                            "logit_source": logit_source,
                            "calibration": calibration,
                            "temperature": (
                                1.0
                                if calibration == "raw"
                                else temperature
                            ),
                            "test_samples": len(test_labels),
                            "accuracy_pct": 100
                            * float(np.mean(predictions == test_labels)),
                            "ece15_pct": 100 * ece(test_labels, probability),
                            "nll": nll(test_labels, probability),
                            "multiclass_brier": multiclass_brier(
                                test_labels, probability
                            ),
                            "aurc": aurc(test_labels, probability),
                        }
                    )
                    confidence, observed_accuracy, mass = reliability_bins(
                        test_labels,
                        probability,
                    )
                    for bin_index, (mean_confidence, mean_accuracy, bin_mass) in enumerate(
                        zip(confidence, observed_accuracy, mass)
                    ):
                        reliability_rows.append(
                            {
                                "dataset": dataset,
                                "configuration": configuration,
                                "seed": seed,
                                "calibration": calibration,
                                "nonempty_bin_index": bin_index,
                                "mean_confidence": mean_confidence,
                                "observed_accuracy": mean_accuracy,
                                "sample_fraction": bin_mass,
                            }
                        )
                    curve_rows.extend(
                        risk_coverage_rows(
                            dataset,
                            configuration,
                            seed,
                            calibration,
                            test_labels,
                            probability,
                            args.risk_coverage_points,
                        )
                    )
                seen_seeds.append(seed)
            audit_rows.append(
                {
                    "dataset": dataset,
                    "configuration": configuration,
                    "observed_seed_count": len(seen_seeds),
                    "observed_seeds": " ".join(
                        str(value) for value in sorted(seen_seeds)
                    ),
                    "target_seeds": args.target_seeds,
                    "target_met": len(seen_seeds) >= args.target_seeds,
                }
            )

    per_run = pd.DataFrame(metric_rows)
    if per_run.empty:
        raise RuntimeError(
            "No controlled logits were found. Provide completed manifest runs "
            "with val_logits.npz/test_logits.npz, or run "
            "export_controlled_logits.py for legacy checkpoints."
        )
    reliability = pd.DataFrame(reliability_rows)
    curves = pd.DataFrame(curve_rows)
    audit = pd.DataFrame(audit_rows)
    summary = metric_summary(per_run)
    changes = paired_calibration_changes(per_run)
    per_run.to_csv(output_dir / "controlled_probability_metrics.csv", index=False)
    summary.to_csv(output_dir / "controlled_probability_summary.csv", index=False)
    changes.to_csv(
        output_dir / "controlled_calibration_paired_changes.csv", index=False
    )
    reliability.to_csv(
        output_dir / "controlled_reliability_bins.csv", index=False
    )
    curves.to_csv(output_dir / "controlled_risk_coverage.csv", index=False)
    audit.to_csv(output_dir / "controlled_calibration_audit.csv", index=False)
    protocol = {
        "temperature_fit_split": "independent validation only",
        "evaluation_split": "test",
        "temperature_type": "single positive scalar per checkpoint",
        "ece_bins": 15,
        "brier_definition": "sum over all classes, averaged over test images",
        "aurc_definition": (
            "trapezoidal area under confidence-ranked selective error versus "
            "coverage; reported as a 0--1 proportion"
        ),
        "risk_coverage_curve_points": args.risk_coverage_points,
        "condition_output_only": True,
        "accepted_logit_sources": [
            "combined_controlled_logits",
            "native_manifest_val_test_logits",
        ],
        "target_seeds": args.target_seeds,
    }
    (output_dir / "controlled_calibration_protocol.json").write_text(
        json.dumps(protocol, indent=2),
        encoding="utf-8",
    )
    if not args.no_figures:
        plot_probability_quality(per_run, output_dir)
        plot_risk_coverage(curves, output_dir)
    print(summary.to_string(index=False))
    print(f"Wrote controlled calibration artifacts to {output_dir}")
    if args.strict_target and not audit["target_met"].all():
        raise SystemExit(
            "Controlled calibration target is not yet met:\n"
            + audit.loc[
                ~audit["target_met"],
                ["dataset", "configuration", "observed_seed_count", "target_seeds"],
            ].to_string(index=False)
        )


if __name__ == "__main__":
    main()
